apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicle-scraper-config
data:
  API_URL: "https://go.bkk.hu/api/query/v1/ws/otp/api/where/vehicles-for-location.json?lat=47.51152389058045&latSpan=0.0536376020654896&lon=19.06933642193823&lonSpan=0.10078281959248159&key=web-54feeb28-a942-48ae-89a5-9955879ebb2c&version=4&appVersion=3.18.0-164644-810354-e3dd8127"
  FETCH_INTERVAL: "10000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-scraper
  template:
    metadata:
      labels:
        app: vehicle-scraper
    spec:
      containers:
      - name: vehicle-scraper
        image: your-docker-image:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: vehicle-scraper-config
              key: API_URL
        - name: FETCH_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: vehicle-scraper-config
              key: FETCH_INTERVAL
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-scraper
spec:
  selector:
    app: vehicle-scraper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080